---
- name: get local IPv4 address
  local_action: setup filter=ansible_default_ipv4
  register: local_ipv4_address

- name: ensure vlad_aux/db_io directories exist
  file:
    path: /var/www/site/vlad_aux/{{ item }}
    state: directory
    mode: 0777
  with_items:
    - db_io
    - db_io/halt_destroy
  sudo: true

- include: debian_mysql.yml
  when: ansible_os_family == "Debian"

- include: redhat_mysql.yml
  when: ansible_os_family == "RedHat"

- include: mysql_import.yml
  tags: mysql_import

- debug: msg="Just a test"
  tags: debug
