language: ruby
rvm:
  - 2.0.0
language: python
python:
  - "2.7"
install:
  - sudo apt-get -y install dkms
  - wget http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo echo "deb http://download.virtualbox.org/virtualbox/debian precise contrib" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update
  - sudo apt-get -y install virtualbox-4.3
  - sudo pip install ansible
  - wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb
  - sudo /etc/init.d/vboxdrv setup
script:
  - sudo vagrant up
  - sudo vagrant halt
  - sudo vagrant destroy -f
after_failure:
  - echo "VirtualBox `VBoxManage --version`"; vagrant --version; ansible --version; vagrant plugin list
