language: ruby
rvm:
  - 2.0.0
language: python
python:
  - "2.7"
install:
  - sudo pip install ansible
  - sudo apt-get update
  - sudo apt-get install virtualbox
  - wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb
  - sudo apt-get install virtualbox-dkms
script:
  - sudo vagrant up
after-script:
  - sudo vagrant halt
  - sudo vagrant destroy
