language: ruby
rvm:
  - 2.0.0
language: python
python:
  - "2.7"
install:
  - sudo pip install ansible
  - sudo apt-get update
  - sudo sh -c "echo 'deb http://download.virtualbox.org/virtualbox/debian '$(lsb_release -cs)' contrib non-free' > /etc/apt/sources.list.d/virtualbox.list" && wget -q http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc -O- | sudo apt-key add - && sudo apt-get update && sudo apt-get install virtualbox-4.3 dkms
  - wget https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.2_x86_64.deb
  - sudo dpkg -i vagrant_1.7.2_x86_64.deb
  - sudo apt-get install linux-generic
  - sudo /etc/init.d/vboxdrv setup
script:
  - sudo vagrant up
  - sudo vagrant halt
  - sudo vagrant destroy -f
after_failure:
  - echo "VirtualBox `VBoxManage --version`"; vagrant --version; ansible --version; vagrant plugin list
