language: ruby
rvm:
  - 2.0.0
language: python
python:
  - 2.7.5
install:
  - sudo pip install ansible
  - sudo apt-get update
  - sudo apt-get install virtualbox
  - sudo apt-get install vagrant
  - sudo apt-get install virtualbox-dkms
script:
  - sudo vagrant up
after-script:
  - sudo vagrant halt
  - sudo vagrant destroy
