---

# Drush make
# ---------------------------------------------------------

# Vlad expects this file to be placed in a subdirectory called "make" within your vlad_aux directory.
# E.g. "vlad_example_d7.make"
# Drush make will not be run if no file is specified.
drush_make_file: ""

# Options to pass to drush make command.
# E.g. "--prepare-install"
# See http://www.drushcommands.com/drush-6x/make/make for possible options.
drush_make_options: ""

# Run drush make every time the VM is provisioned.
# Setting to false will only run drush make if a make file has been specified and docroot is empty (checks for modules directory).
drush_make_force: false
