---
- name: drush | install drush via composer
  shell: composer global require --no-progress --no-interaction drush/drush:6.* chdir=/home/{{ user }}
  register: composer_global_require
  failed_when: "composer_global_require.rc != 0"
  changed_when: "'Nothing to install or update' not in composer_global_require.stdout"

- name: drush | set drush to executable
  file: path=/home/{{ user }}/.composer/vendor/drush/drush mode=775

- name: drush | symlink the drush command so everyone can run it
  file: src=/home/{{ user }}/.composer/vendor/drush/drush/drush dest=/usr/bin/drush state=link
  sudo: true

- name: drush | run drush once as current user to finalise install
  command: drush chdir=/home/{{ user }}
  changed_when: false
  notify: drush cc drush

- name: drush | download the site audit module
  command: drush dl site_audit --destination=/home/{{ user }}/.drush/site_audit --yes chdir=/home/{{ user }}/.drush creates=/home/{{ user }}/.drush/site_audit
  notify: drush cc drush

- name: drush | download the Coder module
  command: drush dl coder-7.x-2.x --destination=/home/{{ user }}/.drush/coder --yes chdir=/home/{{ user }}/.drush creates=/home/{{ user }}/.drush/coder
  notify: drush cc drush

- name: drush | download the Registry Rebuild module
  command: drush dl registry_rebuild --destination=/home/{{ user }}/.drush/registry_rebuild --yes chdir=/home/{{ user }}/.drush creates=/home/{{ user }}/.drush/registry_rebuild
  notify: drush cc drush

- name: drush | get latest version of Drush
  git:
    repo: https://github.com/drush-ops/drush.git
    dest: /home/{{ user }}/drush-master
    depth: 1

- name: drush | set drush to executable
  file: path=/home/{{ user }}/drush-master mode=775

- name: drush | add drush-master alias to .bashrc file
  lineinfile: dest=/home/{{ user }}/.bashrc state=present line='alias drush-master=/home/{{ user }}/drush-master/drush'

- name: drush | add drush7 alias to .bashrc file (matches Acquia Cloud & Pantheon standards)
  lineinfile: dest=/home/{{ user }}/.bashrc state=present line='alias drush7=/home/{{ user }}/drush-master/drush'

- name: drush | run composer install in drush
  command: composer install chdir=/home/{{ user }}/drush-master creates=/home/{{ user }}/drush-master/vendor
