---
- hosts: all
  vars_files:
    - "./vars/defaults/vagrant.yml"
    - "./vars/defaults/general.yml"
    - "./vars/defaults/install.yml"
    - [ "../../settings/vlad_settings.yml", "../../../settings/vlad_settings.yml", "../settings.yml", "vars/dummy_settings.yml" ]
    - [ "../../../settings/vlad_custom_settings.yml", "vars/dummy_settings.yml" ]

  roles:
    - { role: vlad_custom, when: "custom_provision" }

  handlers:
    - include: common/handlers/main.yml
